In [1]:
import pandas as pd
import numpy as np
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
  index=['a', 'c', 'e', 'f'],
  columns=['New York', 'Oregon'])
print(another)

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0


In [3]:
arr = np.arange(12).reshape((3, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
np.concatenate([arr, arr], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
  index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
  index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = np.nan

print(a)
print(b)

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64
f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64


In [7]:
 data = pd.DataFrame(np.arange(6).reshape((2, 3)),
  index=pd.Index(['Ohio', 'Colorado'], name='state'),
  columns=pd.Index(['one', 'two', 'three'],
  name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [17]:
result=data.stack()
print(result)

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64


In [28]:
result.unstack(1)

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [30]:
 df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
  'A': [1, 2, 3],
  'B': [4, 5, 6],
  'C': [7, 8, 9]})
print(df)

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9


In [31]:
melted = pd.melt(df, ['key'])
print(melted)

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9
